- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql-server
    - nginx
    - zip
  - name: start service mysql
    ansible.builtin.service:
      name: mysql-server
      state: started
      enabled: yes
  - name: start service nginx
    ansible.builtin.server:
      name: nginx
      state: started
      enabled: yes
  - name: start service zip
    ansible.builtin.service:
      name: zip
      state: started
      enabled: yes
      

  