- name: demo on sample Idempotency
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present 

  - name: start and enabled nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

